### ISSUE TITLE
hide_version_header setting changes X-Forwarder-For header

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [krakendio/krakend-ce#700] opened 2023-03-30 12:16 UTC
**Environment info:**

* KrakenD version: CE 2.1.4
* System info: docker
* Hardware specs: 8 cores, 16 GB RAM
* Backend technology: Python (FastAPI)

**Describe the bug**
Hello! I discovered very strange and sneaky bug - using [new `hide_version_header` setting](https://www.krakend.io/docs/service-settings/router-options/) changes the `X-Forwarded-For` header. **Not only if you enable this option, but even you disable it explicitly**.

I have next setup:  
`Nginx -> krakend -> gunicorn (app server)`

For example, when I make a request from my browser to backend container through Nginx, I check IP address in `X-Forwarder-For` header in backend app:
```
Docker gateway: 192.168.224.1

No hide_version_header setting:

192.168.224.19    192.168.224.16    192.168.224.13
Nginx          -> krakend        -> gunicorn  ->    application shows x-forwarded-for: 192.168.224.1 (real IP address)


"hide_version_header": true (or even false)

192.168.224.19    192.168.224.16    192.168.224.13
Nginx          -> krakend        -> gunicorn  ->    application  shows x-forwarded-for: 192.168.224.19 (IP address of nginx)
```

**Your configuration file**:
```json
{
  "version": 3,
  "plugin": {
    "pattern": ".so",
    "folder": "/plugins/"
  },
  "extra_config": {
    "security/cors": {
      "allow_origins": ["http*"],
      "allow_methods": [
        "GET", "HEAD", "POST", "PUT", "DELETE", "OPTIONS", "PATCH"
      ],
      "allow_headers": [
          "Origin", "Authorization", "X-Requested-With", "Content-Type",
          "Cache-Control", "Pragma", "Accept-Language", "Accept", "Content-Disposition",
          "language_code"
      ],
      "expose_headers": [ "Content-Length", "Content-Type", "Content-Disposition", "language_code"],
      "allow_credentials": true
    },
    "router": {
      "hide_version_header": true
    }
  },
  "timeout": "10s",
  "cache_ttl": "300s",
  "output_encoding": "no-op",
  "name": "myapp",
  "disable_rest": true,
  "port": 8080,
  "endpoints": [
      {
          "endpoint": "/test",
          "input_query_strings": ["*"],
          "method": "GET",
          "backend": [
            {
                "encoding": "no-op",
                "method": "GET",
                "host": [
                    "http://my_app:8000"
                ],
                "url_pattern": "/test"
            }
          ],
          "input_headers": [
              "JWT", "X-Real-IP", "X-Forwarded-For", "X-Forwarded-Proto", "X-Request-Id", "X-Country-Code", "X-City-Name",
              "User-Agent", "Authorization", "Content-Type", "Accept", "Cookie"
          ]
      }
  ]
}

```

**Commands used**
How did you start the software?
```
docker run \
        -e FC_ENABLE=1 \
        -e FC_SETTINGS="/etc/krakend/settings/" \
        -e FC_PARTIALS="/etc/krakend/partials/" \
        -e FC_TEMPLATES="/etc/krakend/templates/" \
        devopsfaith/krakend:2.1.4 \
        run -c /etc/krakend/krakend.json
```
**Expected behavior**
`hide_version_header` setting does not change `X-Forwarder-For`

**Additional context**  
Everything works good without this part:
```
    "router": {
      "hide_version_header": false
    }
```
Maybe it was already fixed in 2.2.*, but I didn't find a description of such problem

**Comment by taik0** [comment] 2023-03-30 14:43
Hi @alex-pobeditel-2004 

This looks like it's a duplicate of #689 
We are looking to fix it in [lura](https://github.com/luraproject/lura/issues/647).

Thank you for reporting.

**Closed by taik0** 2023-03-30 14:43 UTC

**Comment by alex-pobeditel-2004** [comment] 2023-03-30 17:07
@taik0 thank you for a link on the original problem! It's a pity that I didn't find it before reporting this one :)  
Will watch it for the fix.
